# Build Script for Nginx Ultimate Bad Bot Blocker using GHA
# 
name: CI

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

#services:
#  nginx:
#    image: nginx
    # Map port 8080 on the Docker host to port 80 on the nginx container
#    ports:
#      - 8080:80
      
jobs:
  build:
    #if: "!contains(github.event.head_commit.message, 'skipci')"
    #if: "contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Software
        run: |
          sudo apt -y install dos2unix


      - name: Run build
        shell: bash
        run: |
          echo "export TERM=xterm" >> ~/.bashrc
          source ~/.bashrc
          sudo systemctl enable nginx
          sudo systemctl start nginx
          sudo nginx -t
          sudo systemctl reload nginx
          ./dev-tools/generate-files.sh
          #./dev-tools/install-nginx-1.sh
          ls -la /etc/nginx

      - name: Debug
        shell: bash
        run: | 
          sudo netstat -napt
          cat /etc/nginx/nginx.conf
          sudo systemctl list-units --type=service --all
          #sudo systemctl list-units --type=service --all
          #sudo systemctl list-units --type=service --all
          #sudo systemctl list-units --type=service --all
          #sudo systemctl status nginx.service
          #sudo systemctl status nginx
        if: always()

          
