name: "tagged-release"

on:
  push:
    tags:
      - "V*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Deploy Release"
        run: |
          echo "Deploying"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            README.md
            LICENSE.md
